[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
installCommand = "npm install" # Added install command

[deploy]
startCommand = "npm start"
# Removed healthcheck configuration as it's not strictly necessary for a basic Node.js app on Railway and might require additional setup in your application code.
# healthcheckPath = "/health"
# healthcheckTimeout = 120
# healthcheckInterval = 10
# restartPolicyType = "ON_FAILURE"
# restartPolicyMaxRetries = 5

[variables]
NODE_ENV = "production"